### ISSUE TITLE
Determine why calling vendor proof submission during channel open fails

### ISSUE THREAD

**Issue by postables** [postables/Postables-Payment-Channel#1]
Calling the vendor proof submission function during channel init fails even though proper signature information is passed.

**Comment by postables** [comment]
Bug lies within one of the require statements as the ecrecover logic is returning the correct address, but not passing validation.

**Comment by bonedaddy** [comment]
Issue was intermittent and was due to the `r` and `s` not being padded with bytes from web3py.
Workaround is to convert `r` and `s` to bytes first before converting to hex.
Everything works now  :)
